from itertools import pairwise
from random import randint

# CHATGPT-AAH "trust-me-bro" 1/3 erf computation shit
# (TODO rifai)
import numpy as np
from scipy.special import erf
from scipy.special import erfinv
import matplotlib.pyplot as plt

# -----------------------
# Funzione e derivate
# -----------------------

def f(x):
    return erf(x)

def f_second(x):
    # derivata seconda di erf(x)
    # f'(x) = 2/sqrt(pi) * exp(-x^2)
    # f''(x) = -4x/sqrt(pi) * exp(-x^2)
    return -4 * x / np.sqrt(np.pi) * np.exp(-x**2)

# -----------------------
# Costruzione densità
# -----------------------

def density(x):
    return np.abs(f_second(x))**(1/3)

# -----------------------
# Costruzione nodi
# -----------------------

def compute_nodes(a, b, N, num_grid=5000):
    x_grid = np.linspace(a, b, num_grid)
    rho = density(x_grid)

    # integrale cumulativo (numerico)
    cumulative = np.cumsum(rho)
    cumulative = cumulative / cumulative[-1]  # normalizza a [0,1]

    # target uniformi
    targets = np.linspace(0, 1, N + 1)

    # inversione numerica
    nodes = np.interp(targets, cumulative, x_grid)

    return nodes

# -----------------------
# Polyline
# -----------------------

def build_polyline(x_nodes, x_eval):
    y_nodes = f(x_nodes)
    y_eval = np.interp(x_eval, x_nodes, y_nodes)
    return y_eval, y_nodes

# -----------------------
# Errore L2 discreto
# -----------------------

def compute_error(x_dense, y_true, y_approx):
    return np.mean((y_true - y_approx)**2)

# -----------------------
# MAIN
# -----------------------

N_BINS = 4
N_SAMPLES = 2
Q_DEC = 24 #24 decimal
GAUS_LIMIT = 3
# Maximum number generatable by rng
MAX_RNG = 2**31 - 1

if __name__ == "__main__":
    a = GAUS_LIMIT
    # nodi ottimizzati
    x_nodes = compute_nodes(0, a, N_BINS)

    # valutazione fine
    x_dense = np.linspace(0, a, 2000)
    y_true = f(x_dense)

    y_approx, y_nodes = build_polyline(x_nodes, x_dense)

    error = compute_error(x_dense, y_true, y_approx)

    print("Nodi:", x_nodes)
    print("Errore L2:", error)

    # -----------------------
    # Plot
    # -----------------------

    plt.figure()
    plt.plot(x_dense, y_true, label="erf(x)")
    plt.plot(x_dense, y_approx, '--', label="Polyline approx")
    plt.scatter(x_nodes, y_nodes, zorder=3)

    plt.legend()
    plt.title(f"N={N_BINS}, errore={error:.3e}")
    plt.show()

def arbitrary(x):
    return int(x * (2**Q_DEC))

def write_nums(values, bit_count):
    return ", ".join( f"{bit_count}'d{int(value)}" for value in values )

def compute_m(x, y):
    # we are dividing two qf.f numbers, so we call arbitrary to multiply back the decimal points
    return [ arbitrary((yz_1 - yz) / (xz_1 - xz)) for (xz, xz_1), (yz, yz_1) in zip(pairwise(x), pairwise(y)) ]

# y = m( x - q/m )
def compute_q(x, y, m):
    return [ int(y - m * x / (2.**Q_DEC)) for y, x, m in zip(y, x, m) ]

def rescale_y(y):
    return arbitrary(y)

def rescale_x(x, max):
    return int(x / max * MAX_RNG)

rescaled_limits = [rescale_x(y, max(y_nodes)) for y in y_nodes]
#parsed_limits = parsed_limits[:-1] # ditch last limit (every number greater will be put in last bin)

rescaled_y = [rescale_y(x) for x in x_nodes]
#parsed_x = parsed_x[:-1]

m = compute_m(rescaled_limits, rescaled_y)
q = compute_q(rescaled_limits, rescaled_y, m)
negq_over_m = list(map(lambda qm: -arbitrary(qm[0] / qm[1]), zip(q, m))) # We use this otherwise we end up needing more precision

# FIXME allora quello che ho sbagliato è che c'è da riscalare sull'asse Y, io sto scalanndo su x... Prob ho anche sbahliato i coeff alora diocane vedi graph wikipedia

# FIXME using parsed limits to compute m and q might not be the most precise thing to do...
verilog = f"""
// THIS FILE IS AUTOMATICALLY GENERATED. IT IS NOT ADVISED TO MAKE CHANGES HERE!
localparam N_BINS = {N_BINS};
localparam Q_DEC = {Q_DEC};
localparam NUM_SAMPLES = {N_SAMPLES};
// Numbers coming out of sung are 32 bit, but we use one for sign...
// this could be 31 bit reg instead
// Also we need all the limits otherwise thing get a bit nasty below...
// Limits start from limits[0] = 0
localparam [30:0] limits[N_BINS + 1] = {{ {write_nums(rescaled_limits, 31)} }};
localparam [30:0] q_over_m_coeffs[N_BINS] = {{ {write_nums(negq_over_m, 31)} }};
localparam [30:0] m_coeffs[N_BINS] = {{ {write_nums(m, 31)} }};
localparam [31:0] seeds[NUM_SAMPLES] = {{ {write_nums([randint(0, 2**32 - 1) for i in range(N_SAMPLES)], 31)} }};
////////////////////////////////////////////////////////////////////////////////
"""
 #q computation already takes arbitrary into consideration^^

print(verilog)